# Build settings
permalink   : /blog/:year/:title/

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

gems:
  - jekyll-paginate

# source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Jordan Mecom
description: "Personal site of Jordan Mecom"
url: http://jmecom.github.io
# baseurl: "/end2end"
baseurl: ""

# Author settings
author:
  name      : Jordan Mecom
  thumb     : /images/me.jpg
  url       : http://jmecom.github.io
  github    : http://github.com/jmecom
  linkedin  : http://linkedin.com/in/jmecom

# navbar pages
navbar:
  - slug: resume
    title: Resume
  - slug: projects
    title: Projects
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]